### ISSUE TITLE
mouseButton variable does not store correct values while moving mouse

### ISSUE THREAD

**Issue by danigayo** [benfry/processing4#283] opened 2021-10-04 07:48 UTC
In Processing 3 the following code draws a continuous line while the user is pressing the left button and moving the mouse.

```processing
void setup() {
  fullScreen();
}

void draw() {
  if (mousePressed && mouseButton==LEFT) {
    line(pmouseX,pmouseY,mouseX,mouseY);
  }
}
```

Processing 4 is not able to reproduce the same behavior. 

When the mouse is on the move mouseButton stores 0 and, apparently, the variable only stores "proper" values when the mouse is not moving.

**Comment by benfry** [comment] 2021-10-04 11:06
Duplicate of https://github.com/processing/processing4/issues/281 but that's a good test case, thanks.

**Closed as completed by benfry** 2021-10-04 11:06 UTC
Labels: Duplicate
