### ISSUE TITLE
Cursor don't move with text

### ISSUE THREAD

**Issue by MapMaths** [benfry/processing4#228] opened 2021-07-24 02:20 UTC
This is the latest version of Processing 4
This bug happens no matter if the size of window is big or small

https://user-images.githubusercontent.com/62785981/126854828-759bd9ec-1f4e-450d-a927-23a15ba2ca44.mp4

**Comment by sampottinger** [comment] 2021-07-25 00:57
Herm.... possibly related to #226. Do you mind providing your windows build and display settings in that other bug report? @MapMaths 

https://www.howtogeek.com/236195/how-to-find-out-which-build-and-version-of-windows-10-you-have/

**Comment by MapMaths** [comment] 2021-07-25 03:15
OK
Windows 10 Professional
Version Dev(Sun Valley, about 21H1)
OS Build 21354.1
64-bit operating system, x64-based processor
Windows 10 Feature Experience Pack 321.7601.0.3

**Comment by sampottinger** [comment] 2021-07-26 03:51
Hey @MapMaths! Thank you. Can you confirm if you have screen scaling on?

![processing_cursor](https://user-images.githubusercontent.com/110391/126930679-f8f98aec-4b49-4d8a-a915-60b307984fff.png)

**Comment by benfry** [comment] 2021-07-28 20:16
Closing this as a duplicate of #226.

And there's a separate issue, not connected to display scaling on Windows that's doing the same thing on macOS in #194. Not yet clear if they're identical or separate.

**Closed as completed by benfry** 2021-07-28 20:16 UTC
Labels: Duplicate
