### ISSUE TITLE
can't build on OSX anymore

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#83] opened 2020-04-03 12:03 UTC
I was able to build, but now when I try again it fails. (I did not make any changes).
OSX 10.12.6

`java -version` gives me:

> openjdk version "11.0.6" 2020-01-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

![Screen Shot 2020-04-03 at 13 49 42](https://user-images.githubusercontent.com/738650/78358453-82aa0e00-75b3-11ea-908a-ac66cc78b4a9.png)

> Last login: Fri Apr  3 13:49:22 on ttys002
> Doekes-MBP:~ doekewartena$ /Data/github/processing4/build/macosx/work/Processing.app/Contents/MacOS/Processing ; exit;
> 2020-04-03 13:56:17.623 Processing[55179:2594667] int launch(char *, int, char **) Launchpath: /Data/github/processing4/build/macosx/work/Processing.app/Contents/PlugIns/jdk-11.0.6+10/Contents/Home/lib/jli/libjli.dylib
> 2020-04-03 13:56:17.641 Processing[55179:2594675] int launch(char *, int, char **) Launchpath: /Data/github/processing4/build/macosx/work/Processing.app/Contents/PlugIns/jdk-11.0.6+10/Contents/Home/lib/jli/libjli.dylib
> The version number for the “oauthP5” library is not a number.
> Please contact the library author to fix it according to the guidelines.
> The version number for the “oauthP5” library is not a number.
> Please contact the library author to fix it according to the guidelines.
> The version number for the “oauthP5” library is not a number.
> Please contact the library author to fix it according to the guidelines.
> The version number for the “oauthP5” library is not a number.
> Please contact the library author to fix it according to the guidelines.
> The version number for the “oauthP5” library is not a number.
> Please contact the library author to fix it according to the guidelines.
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
>

**Comment by sampottinger** [comment] 2020-04-09 08:41
This is a duplicate of #73

**Comment by sampottinger** [comment] 2020-04-09 08:42
Will be resolved by #74 when accepted

**Comment by sampottinger** [comment] 2020-04-20 16:46
Hey there! There's a few PRs outstanding (with inter-dependencies) and the build on master has been broken on Mac for some time. So, I have an integration branch over at https://github.com/sampottinger/processing4 master. That branch includes this bug's PR. This allows one to use Processing 4 again on a Mac along with all of the recent bug fixes. For your convenience, I have made builds available at https://www.datadrivenempathy.com/processing.

**Comment by clankill3r** [comment] 2020-04-21 07:48
Ah great, I will clone that then.

**Comment by benfry** [comment] 2020-04-25 21:10
Fixed in https://github.com/processing/processing4/commit/200afc4fd85ccfacd3a178174c4f3462095b8061

**Closed as completed by benfry** 2020-04-25 21:10 UTC
Labels: Duplicate
