### ISSUE TITLE
Accessing Serial Port on Windows Causes JRE Crash

### ISSUE THREAD

**Issue by retiutut** [benfry/processing4#71] opened 2020-02-01 01:36 UTC
## Description

https://github.com/OpenBCI/OpenBCI_GUI/issues/674

## Expected Behavior

Access Serial ports directly on Windows without the JRE crashing.

## Current Behavior

Crashes and produces a log in the application directory. Happens on Standalone app and processing-java.

## Steps to Reproduce

1. Download OpenBCI GUI v4.2.0 pre-release.
2. Open GUI, and hopefully you have some serial ports to populate the list (e.g. COM1, COM2, etc.)
3. In the control panel, click: **Live(from Cyton)-->Serial(from Dongle)-->Manual > -->Any Radio Configuration Button** 

## Your Environment

 

* Processing version: 4.0.0-alpha1
* Operating System and OS version: Windows 10 Pro - up to date
* Other information:

## Possible Causes / Solutions

Probably crashing on the following line:

```
serial_output = new Serial(this, openBCI_portName, openBCI_baud); //open the com port
```

[hs_err_pid11188.log](https://github.com/processing/processing4/files/4142031/hs_err_pid11188.log)
[hs_err_pid2120.log](https://github.com/processing/processing4/files/4142032/hs_err_pid2120.log)

**Comment by retiutut** [comment] 2020-02-02 22:22
Happens using the Processing-IDE and the example from the Processing docs also:

https://processing.org/reference/libraries/serial/Serial.html

**Comment by sampottinger** [comment] 2020-02-03 17:39
Hey @retiutut thanks for posting this! I'll take a look. For folks following along at home, not reproducing on Mac but I'll give it a go on Windows in a minute.

**Comment by retiutut** [comment] 2020-02-03 17:39
That's correct. Seem's to work just fine on Ubuntu Linux and OS X Catalina.

**Comment by sampottinger** [comment] 2020-02-03 17:54
Was able to reproduce on Windows 10 (non JVM access violation!). We will dig in.

**Comment by sampottinger** [comment] 2020-02-03 23:58
Looks like we need to update! https://github.com/java-native/jssc/releases/tag/v2.9.0 or https://github.com/akuhtz/spsw. I'll give it a shot. Just FYI... this fork seems like the active continuation of the now dead original.

**Comment by sampottinger** [comment] 2020-03-03 01:00
See ... https://github.com/sampottinger/jssc. Looks like there's still some work to do here.

**Comment by benfry** [comment] 2020-03-07 22:04
Thanks for looking into it, @sampottinger

**Comment by sampottinger** [comment] 2020-03-08 00:00
Of course! A quick update... I think I sorted it on windows but have mac build issues. Hoping to have more soon.

**Comment by sampottinger** [comment] 2020-03-08 01:38
Blocked on #73

**Comment by sampottinger** [comment] 2020-03-08 19:00
Yay! See the [JSSC migration branch](https://github.com/processing/processing4/tree/jssc_migrate_sampottinger_dep_on_demand). I've tested for Linux 64 bit, Windows 64 bit, and Mac.

<img width="682" alt="Screen Shot 2020-03-08 at 11 59 17 AM" src="https://user-images.githubusercontent.com/110391/76169328-48745a80-6134-11ea-8a86-541dd1a643f5.png">

**Comment by benfry** [comment] 2020-04-27 21:59
Merged the fix from Sam for alpha 2.

**Closed as completed** 2020-04-27 21:58 UTC

**Comment by retiutut** [comment] 2020-04-29 04:39
Awesome! Thanks!

**Comment by retiutut** [comment] 2020-05-02 17:45
@benfry When will alpha 2 release be published?
