### ISSUE TITLE
apple m1 opengl export

### ISSUE THREAD

**Issue by thierry75** [benfry/processing4#414] opened 2022-02-16 02:46 UTC
## Description
apple m1 
macos-aarch64 exported opengl sketch  doen't run

## Current Behavior
LowLevelGLVboInterleaved example run well in processing, export finish without error 

but created app crash with this message:

**java.lang.UnsatisfiedLinkError: Can't load library: /Users/blue/natives/macosx-universal/gluegen_rt**
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2387)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.nativewindow.NativeWindowFactory$1.run(NativeWindowFactory.java:239)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:236)
	at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:69)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:66)
	at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:475)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:147)
	at processing.core.PApplet.initSurface(PApplet.java:10468)
	at processing.core.PApplet.runSketch(PApplet.java:10374)
	at processing.core.PApplet.main(PApplet.java:10132)
	at LowLevelGLVboInterleaved.main(LowLevelGLVboInterleaved.java:190)

this failing directory  /Users/blue/natives doesn't correspond to an existing directory

## Environment

processing 4.0b5
Apple M1 macbookpro 13''
macOs Monterey 12.2.1

## Non working tested solutions (very naive )
i tried to copy in asked directory /Users/blue/natives/macosx-universal/gluegen_rt
anything linked to gluegen without sucess

however, macos-x86_64 version work well, checked gluegen files used, all in the LowLevelGLVboInterleaved.app/Contents/Java/

it sounds different to me, i think,  than other opengl/M1 thread i saw here

**Comment by benfry** [comment] 2022-02-16 23:20
Duplicate of https://github.com/processing/processing4/issues/370

**Closed as completed by benfry** 2022-02-16 23:20 UTC
Labels: Duplicate
