### ISSUE TITLE
On Windows, CTRL + Click on class method name crash/freeze Processing

### ISSUE THREAD

**Issue by nbourre** [benfry/processing4#551] opened 2022-09-09 13:48 UTC
## Description
While coding, I'm used to <kbd>CTRL</kbd>+ Click on method name to access the method implementation. It seems to make Processing unresponsive. I have to kill the `javaw.exe` process via the task manager.

## Expected Behavior
Go to the method implementation or at least do not crash the app.

## Current Behavior
Processing gets unresponsive

## Steps to Reproduce
1. Have a project with classes or clone this [project](https://github.com/nbourre/0sw_processing_exemples/tree/master/s03_pushPopMatrices)
2. Hold <kbd>CTRL</kbd> and click on a method name of an object.
3. The app becomes unresponsive.

## Your Environment
* Processing version: 4.0.1
* Operating System and OS version: Windows 10 Pro (Version	10.0.19044 Build 19044)
* Keyboard settings : English Canada (French Canadian Keyboard)

## Possible Causes / Solutions
* Processing does not crash, but do not respond. It might get into a kind of infinite loop searching for the method name.

**Comment by benfry** [comment] 2022-09-23 19:52
Nuts, ok… Thanks for sharing the example.

**Comment by benfry** [comment] 2022-09-23 20:05
Related: https://github.com/processing/processing4/issues/527

**Comment by benfry** [comment] 2023-07-17 17:39
Closing as duplicate of #527 (will re-open if it's actually a separate problem).

**Closed as completed by benfry** 2023-07-17 17:39 UTC
Labels: Duplicate, Help Wanted, High Priority
