### ISSUE TITLE
Fullscreen does not cover entire screen with P2D

### ISSUE THREAD

**Issue by gravysauce481** [benfry/processing4#753] opened 2023-07-19 04:01 UTC
I am using the fullscreen() method, but when I run the code (in IntelliJ using library jar not Processing) with the 'P2D' argument it doesn't cover the whole screen. The default renderer (no arguments) works as expected but it looks bad and the movement of objects in my game is erratic/jolting.

All that's necessary to reproduce it is "fullscreen(P2D);" in settings() or at the beginning of setup in Processing IDE I think.

I have seen another post similar to this which is supposedly solved except my windows magnification is 125% which seems to be an issue as 100% works but not 125% or 150%.

Adding pixelDensity(displayDensity()); does nothing.

Processing version: 4.2
OS: Windows

**Comment by benfry** [comment] 2023-07-19 12:37
Looks like a duplicate of https://github.com/processing/processing4/issues/718

**Closed as completed by benfry** 2023-07-19 12:37 UTC
Labels: Duplicate
