### ISSUE TITLE
“An error occurred while starting the application” with 4.0a3 on Windows

### ISSUE THREAD

**Issue by TechnicJelle** [benfry/processing4#156] opened 2021-01-18 13:57 UTC
## Description

When I open processing-4.0a3 it shows an error message "An error occurred while starting the application."

## Expected Behaviour

I'd expect it to start up just like processing-4.0a2, which does work normally.

## Current Behaviour

An error message pops up saying "An error occurred while starting the application."

![Untitled](https://user-images.githubusercontent.com/22576047/104923760-cb914e80-599c-11eb-9b40-2aa07d5135d7.png)

## Steps to Reproduce

1. Download 4.0 alpha 3 (17 January 2021) Win 64 from https://processing.org/download/
2. Unzip the file
3. Launch processing.exe

## Your Environment

 

* Processing version: processing-4.0a3
* Operating System and OS version: Windows 10 Education Build 19041.vb_release.191206-1406
* Other information:
CPU: Intel i7-6700k
GPU: Nvidia GeForce GTX 780
RAM: 16 GB 2666 MHz
Java: 
Program Files/Java/jdk1.8.0_251
Program Files/Java/jdk-11.0.8
Program Files/Java/jdk-11.0.9
Program Files/Java/jre1.8.0_271

If there's any more information I can provide, please tell me what and how

**Comment by benfry** [comment] 2021-01-18 15:58
Couple things to check:

* Check to see if `core.jar` is still present in the download directory. Windows Defender has been marking it as malware and removing it. 
* Make sure you're not trying to run the software from *inside* the .zip file (meaning, extract the Processing folder by dragging it from inside the .zip to a location on your machine).
* Anything else from the Troubleshooting page: https://github.com/processing/processing/wiki/Troubleshooting

**Comment by TechnicJelle** [comment] 2021-01-18 16:17
1. core.jar is present in the folder at this location: processing-4.0a3\core\library\core.jar
2. I have unpacked the files, and I am running them from inside a folder on my desktop.
3. - Renaming my sketchbook did not solve the issue.
   - Deleting my preference file did also not solve the issue.
   - I have an M.2 NVMe drive, so I don't suspect "an exceptionally large sketchbook folder" is the problem. It's only 1.22 GB big, anyway.
   - I am using Windows Defender, but I haven't heard anything from it regarding Processing.
<details>
<summary>launch4j.log</summary>



```
Version:	3.9
CmdLine:	C:\Users\TechnicJelle\Desktop\Processing\processing-4.0a3\processing.exe --l4j-debug
WOW64:		yes
Working dir:	C:\Users\TechnicJelle\Desktop\Processing\processing-4.0a3\.
Bundled JRE:	java
Check launcher:	C:\Users\TechnicJelle\Desktop\Processing\processing-4.0a3\java\bin\javaw.exe (OK)
Heap -Xmx:	Requested 512 MB / 0%, Available: 7792 MB, Heap size: 512 MB
Add classpath:	lib\pde.jar
Add classpath:	core\library\core.jar
Add classpath:	lib\jna.jar
Add classpath:	lib\jna-platform.jar
Add classpath:	lib\antlr-4.7.2-complete.jar
Add classpath:	lib\ant.jar
Add classpath:	lib\ant-launcher.jar
Launcher:	C:\Users\TechnicJelle\Desktop\Processing\processing-4.0a3\java\bin\javaw.exe
Launcher args:	-Xmx512m -Djna.nosys=true -Dsun.java2d.uiScale.enabled=false -Djna.boot.library.path=lib -Djna.nounpack=true -Dsun.java2d.d3d=false -Dsun.java2d.ddoffscreen=false -Dsun.java2d.noddraw=true -classpath "lib;lib\pde.jar;core\library\core.jar;lib\jna.jar;lib\jna-platform.jar;lib\antlr-4.7.2-complete.jar;lib\ant.jar;lib\ant-launcher.jar" processing.app.Base
Args length:	354/32768 chars
Error msg:	An error occurred while starting the application.
```


</details>

Thank you for replying so fast!
I hope this is useful information!

**Comment by benfry** [comment] 2021-01-18 16:40
Try opening a command prompt, and `cd` to the Processing folder (the one with `processing.exe` in it). Then paste this in and hit return: 

```
.\java\bin\java.exe -cp lib/pde.jar;core/library/core.jar;lib/jna.jar;lib/jna-platform.jar;lib/antlr-4.7.2-complete.jar;lib/ant.jar;lib/ant-launcher.jar -Djna.nosys=true -Dsun.java2d.uiScale.enabled=false -Djna.boot.library.path=lib -Djna.nounpack=true -Dsun.java2d.d3d=false -Dsun.java2d.ddoffscreen=false -Dsun.java2d.noddraw=true processing.app.Base
```

That'll manually start the software and may provide more clues about what's going on.

**Comment by TechnicJelle** [comment] 2021-01-18 17:03
That did it! It started up nicely now! And my sketches work perfectly!
I can't seem to get it to generate a new launch4j.log, though

**Comment by benfry** [comment] 2021-01-18 17:31
Nuts; sounds like a problem with the launch4j wrapper.

**Comment by benfry** [comment] 2021-01-18 17:34
Are you running the software from a folder/path that contains non-ASCII characters?

**Comment by TechnicJelle** [comment] 2021-01-18 18:05
I'm running it from `C:\Users\TechnicJelle\Desktop\Processing\processing-4.0a3\processing.exe`, so I really don't think there are any non-ASCII character in there. I could try moving it to `C:\processing-4.0a3\processing.exe` to see if that helps?

**Comment by benfry** [comment] 2021-01-18 18:23
Sure, worth a try… 

Oh, also try replacing `.\java\bin\java.exe` in that command above with just `java` (no dot in front, etc) and see what happens. Just in case the launcher is trying to use a different version of Java on your machine.

**Comment by TechnicJelle** [comment] 2021-01-18 18:31
Running it from `C:\processing-4.0a3\processing.exe` did not yield any different results.

`C:\processing-4.0a3>java -cp lib/pde.jar;core/library/core.jar;lib/jna.jar;lib/jna-platform.jar;lib/antlr-4.7.2-complete.jar;lib/ant.jar;lib/ant-launcher.jar -Djna.nosys=true -Dsun.java2d.uiScale.enabled=false -Djna.boot.library.path=lib -Djna.nounpack=true -Dsun.java2d.d3d=false -Dsun.java2d.ddoffscreen=false -Dsun.java2d.noddraw=true processing.app.Base` also launches Processing normally like it should.

**Comment by benfry** [comment] 2021-01-18 19:47
Nuts; ok… Sounds like the solution is to swap out launch4j for another launcher on Windows. We'll have to see how pervasive this is.

In the meantime, you can put the original line I shared into a `.bat` file so you have something to double-click to start things up.

**Comment by TechnicJelle** [comment] 2021-01-18 20:01
I hope this fix is easy

And in the meantime, I think I'll just stick with alpha 2. Or the stable version. Those both work perfectly fine still.

**Comment by cacheflowe** [comment] 2021-01-18 20:07
I got this startup error too and was about to report it. I had the same successful manual startup results with the bundled `java.exe` command noted above, but a failure with the system `java` command, as I have `java version "1.8.0_251"` as my default system Java version.

**Comment by benfry** [comment] 2021-01-18 21:29
Oh… I have an idea. Try renaming the `java` folder in this release, and then copying the `java` folder from the alpha 2 release over instead. It might be the release number…

**Comment by TechnicJelle** [comment] 2021-01-18 21:32
No luck... Still doesn't work

**Comment by cacheflowe** [comment] 2021-01-18 21:40
No luck here either :(

**Comment by benfry** [comment] 2021-01-18 21:59
Nuts; thought that would be it—this newest Java release is 11.0.9.1 (has an extra digit at the end) so I thought that may have been the cause.

**Comment by benfry** [comment] 2021-01-18 22:21
Ok, it's the `processing.exe` file. You can copy `processing.exe` from alpha 2 and it'll work fine.

Which means that it was broken by… the updated splash screen image.

**Closed as completed** 2021-01-18 22:39 UTC

**Comment by benfry** [comment] 2021-01-18 22:53
New build (and replacement `processing.exe` file) posted at https://github.com/processing/processing4/releases/tag/processing-1272-4.0a3
