### ISSUE TITLE
Examples >  BeginEndContour and others: using P2D with createShape: GLException GLBufferObjectTracker.mapBuffer (Linux)

### ISSUE THREAD

**Issue by Sciss** [benfry/processing4#353] opened 2022-01-19 22:14 UTC
## Description

Running the 'BeginEndContour' example included with Processing. On Linux I get an exception.

```
GLException: GLBufferObjectTracker.mapBuffer(): GL_INVALID_VALUE Invalid values: offset 0, length 0, buffer storage of target 0x8892 -> 10: GLBufferStorage[name 10, size 0, mutable usage 0x88E8, mapped null]
```

## Your Environment

Using the official binary download.

* Processing version: 4.0b3
* Operating System and OS version: Debian 11
* Other information: Wayland

```
$ uname -a
Linux aleph 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
```

**Comment by Sciss** [comment] 2022-01-19 22:16
Actually that happens with other examples that use `size(640, 360, P2D)` rather than `size(640, 360)`: `GroupPShape`, `PathPShape`, `PolygonPShape`. Whereas `ParticleSystemPShape` does not have an issue. I think the problem is `createShape`.

**Comment by benfry** [comment] 2022-01-19 23:14
Thanks for the report… tagging @codeanticode, looks like we have a nasty regression or two in the OpenGL updates in beta 3.

**Comment by codeanticode** [comment] 2022-01-20 00:24
Ok, working on it.

**Comment by codeanticode** [comment] 2022-01-23 03:05
Fixed with this [PR](https://github.com/processing/processing4/pull/367)

**Comment by benfry** [comment] 2022-01-23 03:06
Cool, will merge first thing in the morning.

**Comment by benfry** [comment] 2022-01-23 11:27
All set for beta 4, thanks!

**Closed as completed by benfry** 2022-01-23 11:27 UTC
Labels: OpenGL
