### ISSUE TITLE
Resize cursor not showing when resizing sketch.

### ISSUE THREAD

**Issue by dman2210** [benfry/processing4#705] opened 2023-04-24 20:37 UTC
## Description
The mouse cursor is not displayed correctly when resizing the window. The arrow cursor is shown instead of the east-west resize cursor.

## Expected Behavior
The mouse cursor changes to east-west resize cursor at the edge of the window where it can be resized.

## Current Behavior
The mouse cursor does not change.

## Steps to Reproduce
1.  set `surface.setResizable(true);` 
2. run the sketch. move your cursor to the edge of the window.

## Your Environment
* Processing version: 4.0.1
* Operating System and OS version: Windows 11 10.0.22621 Build 22621
* 
I believe it is a windows only issue but I have not checked.

https://user-images.githubusercontent.com/32994314/234109470-3b98d530-e1cb-4c34-bd65-631bcf40069c.mp4

_Originally posted by @dman2210 in https://github.com/processing/processing4/issues/657#issuecomment-1520786641_

**Comment by benfry** [comment] 2023-07-16 18:00
What renderer are you using? Does this still occur with 4.2?

**Comment by benfry** [comment] 2023-07-17 17:46
Closing as duplicate of https://github.com/processing/processing4/issues/657

**Closed as completed by benfry** 2023-07-17 17:46 UTC
Labels: Duplicate, Windows
