### ISSUE TITLE
Cannot type quotes when using US Keyboard on a Dutch installation of macOS Monterey

### ISSUE THREAD

**Issue by ajvdmeij** [benfry/processing4#566] opened 2022-10-02 19:09 UTC
## Description
Quotation marks don't work if I use the US keyboard 

## Expected Behavior
I use US Keyboard on my mac: System Preferences -> Language and Regions and then The Keyboard preferences (not sur it this is the right term, I use a Dutch version). 

## Current Behavior
In a sketch the quotation marks don't show then. If I change the Keyboard back to Dutch, it works again

## Steps to Reproduce
1. On a mac set Keyboard Prefernces to US
2. Start Processing
3. Type quotations marks ""

## Your Environment
* Processing version: 4
* Operating System and OS version: Mac Os Monterey
* Other information:

## Possible Causes / Solutions
No sorry

**Comment by SableRaf** [comment] 2022-10-05 14:17
Sorry to ask a somewhat silly question but: have you tried in another text editor? Can you get the quotation marks to show in TextEdit for example?

**Comment by benfry** [comment] 2023-01-16 17:04
Appears to be a duplicate of https://github.com/processing/processing4/issues/322

**Closed as completed by benfry** 2023-01-16 17:04 UTC
Labels: Duplicate, Help Wanted

**Comment by ajvdmeij** [comment] 2023-01-16 17:32
Thanks for the mail! Your work around seems to work!

Arjan

Op ma 16 jan. 2023 om 18:04 schreef Ben Fry ***@***.***>:

**Comment by benfry** [comment] 2023-01-16 20:16
Thanks for letting me know!
