### ISSUE TITLE
Processing 4 IDE Wrong Caret Pos with 125% Text

### ISSUE THREAD

**Issue by RichardDL99** [benfry/processing4#359] opened 2022-01-21 10:25 UTC
Processing 4.0b2 on W10.  On Windows, Settings, System, Display, Scale and Layout, Change the size of text, apps and other items. The normal setting is 100% and the recommended setting is 125%.  I've been using 125% for a long time. With Processing 3 there is no issue, but Processing 4 IDE is confused.

If you have a long line of source code, click somewhere near the end, type another character, it inserts a few chars to the left.  The position shown by the caret and the insertion point are different.

If you use a long line of e.g. 'A', not recognised as source code, it's shown a different size, and the caret is shown correctly.

There are two other symptoms of this.  On the initial Processing splash screen, the text is blurred.  On the IDE tab names, the text is pixelated.

**Comment by benfry** [comment] 2022-01-21 11:05
Duplicate of https://github.com/processing/processing4/issues/342, which is fixed for the next release. In the meantime, check “Disable HiDPI Scaling” in Preferences and restart.

**Closed as completed by benfry** 2022-01-21 11:05 UTC
Labels: Duplicate
