### ISSUE TITLE
PDF export not working with Processing 4.0 beta 5

### ISSUE THREAD

**Issue by rantonse** [benfry/processing4#395] opened 2022-02-05 18:25 UTC
## Description

PDF export does not work with Processing 4.0 beta 5. 

## Expected Behavior

A PDF file with dimensions corresponding to the canvas size is expected.

## Current Behavior

The dimensions of the resulting PDF file is 0 × 0.

## Steps to Reproduce
```
import processing.pdf.*;

void setup() {
  size(600, 600);
  beginRecord(PDF, "line.pdf");
  background(255);
  stroke(0);
  strokeWeight(20.0);
  line(0, 0, width, height);
  endRecord();
}
```

## Your Environment
* Processing version: 4.0 beta 5
* Operating System and OS version: MacBook Pro (16-inch, 2021), macOS Monterey 12.2

**Comment by benfry** [comment] 2022-02-05 23:31
Confirmed; very odd, have not been in that code. Was it behaving with beta 4 or 3?

**Comment by rantonse** [comment] 2022-02-05 23:43
It has worked perfectly fine with beta 4 and 3.

**Comment by jaegonlee** [comment] 2022-02-06 11:39
The size of exported pdf is 0 x 0.
The dimension of PGraphicsPDF is set by `pg.setSize(w,h)`(in PApplet.java), but width and height of PGraphicsPDF is not changed.

**Comment by benfry** [comment] 2022-02-06 12:42
Yeah, it was a regression caused by the changes for https://github.com/processing/processing4/issues/186. 

Now fixed for beta 6.

**Closed as completed** 2022-02-06 12:41 UTC
