### ISSUE TITLE
File > Open crashes on Fedora 35 with 4.0b2

### ISSUE THREAD

**Issue by mario6097** [benfry/processing4#333] opened 2022-01-06 16:12 UTC
please see at https://discourse.processing.org/t/processing-4-0b2-crashes-on-fedora-35/34472

On my Fedora 35, processing-4.0b2 crashes any time I try to open a file.

## Steps to Reproduce
1. launch processing 
2. try to open a file from file/open

## Your Environment
Linux localhost.localdomain 5.15.11-200.fc35.x86_64
Processing 4 (beta)  4.0b2

**Comment by benfry** [comment] 2022-01-11 00:18
Closing as duplicate of https://github.com/processing/processing4/issues/306

**Closed as completed by benfry** 2022-01-11 00:18 UTC
