### ISSUE TITLE
relying on default charset to be consistent across instances

### ISSUE THREAD

**Issue by ratchetfreak** [benfry/processing4#332] opened 2022-01-05 16:14 UTC
https://github.com/processing/processing4/blob/019143a33b150f2f832c689bba7b651b490201dd/java/libraries/net/src/processing/net/Client.java#L694-L696

java.lang.String.getBytes() relies on the default charset which is not necessarily consistent between instances. This should be fixed to a portable standard charset

```
  public String readString() {
    byte b[] = readBytes();
    if (b == null) return null;
    return new String(b, StandardCharset.UTF_8); // or whatever charset you want to fix it to
  }

  public void write(String data) {
    write(data.getBytes(StandardCharset.UTF_8)); // must match readString
  }
```

**Comment by benfry** [comment] 2022-01-11 00:26
Duplicate of https://github.com/processing/processing4/issues/336

**Closed as completed by benfry** 2022-01-11 00:26 UTC
Labels: Duplicate
