### ISSUE TITLE
noSmooth() wrongly reports that it was invoked outside settings()

### ISSUE THREAD

**Issue by PixelCatalyst** [benfry/processing4#164] opened 2021-01-21 20:42 UTC
## Description

When using `noSmooth()` as described in Processing reference (inside `setup()` and after `size()` was called) the error message is shown in the console "noSmooth can only be used inside settings". This is not true, cause the sketch was run inside PDE and according to docs and code comments this is the correct method to disable smoothing. 

Code to replicate:
```
void setup() {
 size(500, 500);
 
 noSmooth();
}
```

## Your Environment

 

* Processing version: Processing4 built up to commit e96622d
* Operating System and OS version: Windows 10 build 19042.685

## Possible Causes / Solutions

Possibly connected to #163 and/or #161

**Comment by dzaima** [comment] 2021-01-21 21:12
This is definitely the same issue as #163 - the preprocessor failed to move `noSmooth` from settings to setup, causing both it doing nothing, and giving the error that it's outside of settings. This has since been fixed, and `noSmooth` works fine in the latest alpha.

**Comment by benfry** [comment] 2021-04-29 19:06
Closing as duplicate of #163.

**Closed as completed** 2021-04-29 19:06 UTC
Labels: Duplicate
