### ISSUE TITLE
Illegal reflective access by processing.app.platform.LinuxPlatform

### ISSUE THREAD

**Issue by CatInAHatIsBack** [benfry/processing4#343] opened 2022-01-15 15:53 UTC
System : x86 Archo Linux, xfce
Editor : code-oss
Java version : openjdk 17.0.1
Processing 4

Unsure of what to do, going to continue debugging to see if i can figure it out.

WARNING: Illegal reflective access by processing.app.platform.LinuxPlatform (file:/home/processing/processing-4.0b2/lib/pde.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of processing.app.platform.LinuxPlatform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by benfry** [comment] 2022-01-15 16:01
Duplicate of https://github.com/processing/processing4/issues/207

**Closed as completed by benfry** 2022-01-15 16:01 UTC
Labels: Duplicate

**Comment by CatInAHatIsBack** [comment] 2022-01-17 23:47
I appologize, I did not see it had already been raised as an issue. it was
also my fault. I couldnt get it to run because I messed up some settings
and thought the error message was the reason it wouldnt run.

The library is great and I thank you for your your help.

//====================================================//
Question below is only if you have time for another dumb question.

As I am unsure of exacly how it runs yet, I might very vell just have
messed up the setup. But i am having some well i would be sceptical to call
it lag, more like long startup times and 10+ seconds to close a window.
Once a window is up and running there is generally no problems. Is this a
problem you have encountered before?

**Comment by benfry** [comment] 2022-01-18 00:45
No worries, the search on here isn't the easiest. 

I haven't seen long lags like that on Linux; only on Windows where virus checking kicks in and wants to aggressively scan sketches that use OpenGL. I'd check with https://discourse.processing.org/ for troubleshooting help like that though.
