### ISSUE TITLE
PApplet not showing after mac os ventura upgrade

### ISSUE THREAD

**Issue by WhiteSte** [benfry/processing4#584] opened 2022-10-27 12:37 UTC
## Description

Hi, I updated mac os to the new version and when running processing as external lib in java environment, PApplet is not showing anymore. I can see that software runs in console, if I press some keys I trigger actions, I can see the PApplet app is running inside the opened app menu (lower-right of app bar, near the bin), but the canvas is totally disappeared. 

If i run an example from the official processing editor it works!

## Steps to Reproduce

1. Update mac os to ventura
2. Run a processing example inside java/eclipse environment
3.

## Your Environment

 

* Processing version: the last 4.1
* Operating System and OS version: Mac os ventura

**Comment by SableRaf** [comment] 2022-10-27 16:19
Hi and thanks for your report :) I believe this is may be a duplicate of https://github.com/processing/processing4/issues/544

**Comment by WhiteSte** [comment] 2022-10-28 14:31
yeah, didn't saw there was an existing issue request!

**Comment by benfry** [comment] 2022-11-04 17:54
Closing as duplicate of #544.

**Closed as completed by benfry** 2022-11-04 17:54 UTC
Labels: Duplicate
