### ISSUE TITLE
IDE cursor position is wrong if font size is changed in preferences on macOS

### ISSUE THREAD

**Issue by thierry75** [benfry/processing4#194] opened 2021-05-07 20:16 UTC
## Description
in preferences, settings a higher value in "Editor font size" results in having cursor blinking not at the real position, typing will result in inserting code at the wrong place

## Expected Behavior
typing code where the cursor blink
## Current Behavior
actual cursor is not where the cursor blink

## Steps to Reproduce
set Editor font size to 14

## Your Environment

* Processing version: 4.03
* Operating System and OS version: macOs Big sur and mojave
* Other information: macbook pro

**Comment by benfry** [comment] 2021-06-28 11:08
I'm not seeing this on my Mojave machine. What font are you using?

**Comment by sampottinger** [comment] 2021-07-25 01:11
Unable to reproduce in 11.4 on the default monospace font. Was this still a problem for you @thierry75?

![Screen Shot 2021-07-24 at 6 11 00 PM](https://user-images.githubusercontent.com/110391/126884598-a3d27992-a594-40a0-8b8f-ca71423a3bcd.png)

**Comment by benfry** [comment] 2021-07-28 20:17
Saw this on someone else's macOS machine, but then wasn't able to reproduce it again. Also not sure if it's something when Processing 4 first runs, and a subsequent launch it's behaving better because `preferences.txt` has been updated properly. 

Also not sure if it's the same as #226, but at the moment I suspect they're different. A lot has changed in the font sizing and prefs code—there was lots of badness in there, but clearly there's a regression.

**Comment by benfry** [comment] 2021-08-01 15:00
For anyone having this issue on macOS, were you using a second display?

**Comment by simuloid** [comment] 2021-08-31 23:37
I also have an issue with the cursor position after changing font size, but I'm on Windows 10 Home using Processing 4.0b1

What I find is that the cursor position gets increasingly wrong the further to the right in the editor window you go.
This is true regardless of whether I use the original font or "fixed" or "Lucida Console". I have tried it with font size 12, 14, and 18.
In fact, I can't seem to get it back to a working state.

To repeat the problem:
Type in the line
//345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
Place the cursor at the beginning of the line and then:
1) use the right arrow to move the cursor 6 spaces.
2) The cursor will move so that it is between the first 6 and 7. Type "a" and you will see the "a" appear where the cursor is.  Hit backspace to get rid of that "a".
3) Repeat steps 1 and 2 and notice that the cursor eventually is not actually between characters, but over them. Also, it is well to the right of the place where the "a" actually gets inserted.

**Comment by samborkent** [comment] 2021-09-07 12:41
> I also have an issue with the cursor position after changing font size, but I'm on Windows 10 Home using Processing 4.0b1
> I have 2 monitors, my primary is my laptop screen, my secondary is an external LCD 1080p HDMI thing. When I drag my Processing IDE onto the second monitor, the cursor behaves properly but the text looks terrible. When I have the window on my laptop screen, the text looks great but the cursor behaves as described below.
> 
> What I find is that the cursor position gets increasingly wrong the further to the right in the editor window you go.
> This is true regardless of whether I use the original font or "fixed" or "Lucida Console". I have tried it with font size 12, 14, and 18.
> In fact, I can't seem to get it back to a working state.
> 
> To repeat the problem:
> Type in the line
> //345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
> Place the cursor at the beginning of the line and then:
> 
> 1. use the right arrow to move the cursor 6 spaces.
> 2. The cursor will move so that it is between the first 6 and 7. Type "a" and you will see the "a" appear where the cursor is.  Hit backspace to get rid of that "a".
> 3. Repeat steps 1 and 2 and notice that the cursor eventually is not actually between characters, but over them. Also, it is well to the right of the place where the "a" actually gets inserted.

I am having the same problem, also running Processing 4.0b1 on Windows 10 Home, but I also have it when I don't have a second monitor connected.

![image](https://user-images.githubusercontent.com/79200057/132346127-6391ea0d-5705-4179-9eba-28fc0022cd56.png)

Image showing the problem, when trying to set up PeasyCam.

**Comment by kgmuzungu** [comment] 2021-09-14 07:32
Having the same problem as described above. Windows 10, Processing 4.0b1. no second display

**Comment by allantarcy** [comment] 2021-09-23 08:08
I have changed the font size to 10. Now it seems to work. I hope it will help you.

**Comment by spipsdew** [comment] 2021-09-30 01:48
Changing the font size to 10 fixed it for me on windows with my single monitor.

**Comment by pekisic** [comment] 2021-10-02 12:23
It is the issue with the 4K screen resolution, as well as dual monitors on different resolutions.

 I've changed the font size to 18 and switch to the monitor with 1920 by 1080 resolution and had no issues in editor. However, my dropdown menus are still appearing on my other 4K monitor with overlapping rows. When I move the editor on the 4K screen the drop-down menus are ok but the text in the editor starts to bug. So, for coding I use the HD monitor and for the menus I'm using a 4K monitor.

It is pretty inconvenient, and difficult to work. 
I hope that they will resolve this issue ASAP.

**Comment by benfry** [comment] 2021-10-05 02:12
Folks, like the title says, this is *only* about macOS. There's at least one separate issue for Windows. The problem there is almost completely unrelated, even though the effect sounds similar. If you have Windows trouble, check this issue: https://github.com/processing/processing4/issues/226. If that doesn't describe what you're seeing on Windows, please file a new issue.

Posts about Windows in this issue will be removed to avoid confusion.

**Comment by benfry** [comment] 2021-10-05 02:14
@allantarcy @pekisic are you using macOS or Windows?

**Comment by allantarcy** [comment] 2021-10-05 05:20
> @allantarcy @pekisic are you using macOS or Windows?

Ow my bad sorry I'm on Windows

**Comment by pekisic** [comment] 2021-10-05 06:46
@allantarcy @benfry On Windows...

**Comment by benfry** [comment] 2021-10-05 12:19
Got it, thanks for clarifying. I'll remove those so we can keep this one specific to the macOS issue. Definitely check https://github.com/processing/processing4/issues/226 in case it's the same problem, or file something new if you're seeing different behavior.

**Comment by allantarcy** [comment] 2021-10-20 04:37
> I am also seeing this issue-windows, and font size does not appear to influence it, but changing windows display scaling to 100% seems to help. It seems I can't set it per application

You should go on  #226 this thread is for Mac issues

**Comment by benfry** [comment] 2022-01-10 23:47
**If you're having this problem on Windows**, please see https://github.com/processing/processing4/issues/226. 

This issue is for macOS—which is a totally unrelated problem. To keep things sane, non-macOS comments to this issue have been removed.

**Comment by tmatinla** [comment] 2022-01-24 20:41
Confirming this happens for me with macOS with 4.0 beta 4. (This is Monterey 12.1 on Intel Mac, 16" late 2019 model)

After setting the font size in preferences, the cursor position is not correct:

<img width="626" alt="kuva" src="https://user-images.githubusercontent.com/1188966/150855548-af5302f7-bac3-4d45-adc7-13cc4755ba8d.png">

> Also not sure if it's something when Processing 4 first runs, and a subsequent launch it's behaving better because preferences.txt has been updated properly.

The problem does not go away if I restart Processing.

> For anyone having this issue on macOS, were you using a second display?

I have couple of external displays. The problem actually shows only in the laptop's screen. If I move the window to an external display, the problem goes away (and comes back if I move the window back to laptop's screen).

The problem still happens if I unplug the external displays. Also changing resolution seems not to make any difference.

**Comment by benfry** [comment] 2022-01-24 20:47
Ok, I think it's getting the character widths from the wrong display. Does it work correctly on the "main" display? On macOS that might be the display with the menubar, or dock, or where the Editor window first showed up.

**Comment by benfry** [comment] 2022-01-24 21:46
Also, can you confirm whether it's broken the same way on beta 3 and beta 4? I'm wondering if the fixes for the Windows side have exacerbated this problem a bit.

**Comment by tmatinla** [comment] 2022-01-25 08:45
> Does it work correctly on the "main" display?

No, it does not; my "main" display is the laptop's screen where the problem shows.

> confirm whether it's broken the same way on beta 3 and beta 4

No, for me, in beta 3 it's actually the other way around: it works on laptop's screen ("main" display), but if I move the window to an external screen then the problem is there (although cursor offset is a little bit different compared to beta 4, but that's probably due to different resolutions).

(I could try run this in debugger if there's something specific to look for.)

**Comment by benfry** [comment] 2022-01-25 12:13
Thanks, that's the information I need for now. Seems we're having a problem with the per-display info about text sizes. A previous change made it work on macOS, but broke the Windows version even for users without a secondary display, so that was more serious. Will look into it.

**Comment by benfry** [comment] 2022-01-28 19:09
Ok, digging into this a bit more, and confirmed that it's not just external displays that cause the issue. 

Workarounds for the time being:

1. Visit Preferences, and select a different font than Source Code Pro. Most others don't have this fractional scaling issue. They may not be as nice, but it seems that Source Code Pro _really_ wants to use fractional metrics.
2. Also inside Preferences, you'll find that not all font sizes have this issue. On my machine, 12 and 18 were fine, but 14 made things a mess. You'll have different results on different machines.

On a positive note, I'm able to reproduce the issue which makes it drastically easier for me to fix. On the negative side, it's a nasty one. :)

**Comment by benfry** [comment] 2022-01-29 17:44
Fixed with https://github.com/processing/processing4/commit/c6d9ba0c7f74739ef684db2effe447ef25b5bb32 for 4.0 beta 5. Phew!

**Closed as completed by benfry** 2022-01-29 17:44 UTC
Labels: macOS
