### ISSUE TITLE
Text cursor in wrong position when Windows display set to 125% (works when 100%)

### ISSUE THREAD

**Issue by Albert** [benfry/processing4#277] opened 2021-10-01 06:56 UTC
## Description
Fresh install on computer.  Windows display is set to 125%.  When I type "asdf" over and over again the text cursor drifts to the right.

https://user-images.githubusercontent.com/19919/135577967-20be3063-e55d-4f23-90c9-ad9d772272ba.mp4

## Expected Behavior
I'd expect the cursor to be right at the right edge of my text

## Current Behavior
The text cursor drift rightwards, more so the longer the line.

## Steps to Reproduce
1. Type a long line

## Your Environment
* Processing version: 4.0b1
* Operating System and OS version:  Fresh factory reset on an MSI laptop, Windows 10, 
* Other information:

**Comment by Albert** [comment] 2021-10-01 18:15
Oh, just noticed this issue open in `processing/processing` as well:

https://github.com/processing/processing/issues/6223

**Comment by benfry** [comment] 2021-10-03 20:49
Closing as duplicate of https://github.com/processing/processing4/issues/226

**Closed as completed by benfry** 2021-10-03 20:49 UTC
Labels: Duplicate
