### ISSUE TITLE
[P2D] fullScreen not working correctly

### ISSUE THREAD

**Issue by clankill3r** [benfry/processing4#623] opened 2022-12-17 10:42 UTC
OSX 10.15.7
Processing 4.1.1

<img width="534" alt="Screenshot 2022-12-17 at 11 40 09" src="https://user-images.githubusercontent.com/738650/208237850-b66d017b-ac74-4795-bff0-1fe2e41929a9.png">

```java
void setup() {
  fullScreen(P2D, 1);
  background(255,0,0);
}
```

width and height is reported correctly.

**Comment by clankill3r** [comment] 2022-12-19 09:22
Ok this is messed up.
I had my screen arrangement like this:

<img width="277" alt="Screenshot 2022-12-19 at 10 15 16" src="https://user-images.githubusercontent.com/738650/208390652-e984274c-31e6-4b3b-ae74-133e5a046d74.png">

The fullscreen part happens in the red:
<img width="277" alt="Screenshot 2022-12-19 at 10 15 16 copy" src="https://user-images.githubusercontent.com/738650/208390862-0ec6bf61-2900-456d-9e10-b99d3b06e69d.png">

Even a slight change fixed it, with this fullScreen works correct.

<img width="296" alt="Screenshot 2022-12-19 at 10 15 34" src="https://user-images.githubusercontent.com/738650/208390579-3119040c-a807-4c09-94de-637663dd81e5.png">


Ok,  just found this: https://github.com/processing/processing4/issues/471 ...

**Comment by benfry** [comment] 2023-01-09 22:17
Ok, closing as duplicate of #471.

**Closed as completed by benfry** 2023-01-09 22:17 UTC
Labels: Duplicate
