### ISSUE TITLE
Pressing Ctrl-key and click on a word crashes PDE if character 'ä' is used.

### ISSUE THREAD

**Issue by toniholzer** [benfry/processing4#682] opened 2023-03-04 14:36 UTC
## Description
Pressing Ctrl-key and click on a word crashes PDE if character 'ä' is used.

## Expected Behavior
Pressing Ctrl-key and click on a word opens a window 'usage of ...'.

## Current Behavior
Sketch crashes under processing v4.x if you insert character 'ä'
and press Ctrl-key and click on a word.

## Steps to Reproduce
/*  file: Processing_v4_bug.pde   
Copy this example to PDE.
Press Ctrl-key and click on word 'text'
A window 'Usage of height' opens under processing v3.x.
With processing v4.x the sketch crashes!
Reason is the usage of character 'ä'.
If you delete it, all is working fine.
*/
void setup()
{ size(100, 80, P3D); }
void draw() 
{ background (55);
  text(frameCount,22,22);
}

## Your Environment
* Processing version:  4.x
* Operating System and OS version: Window-10

## Possible Causes / Solutions
Delete character 'ä' and try again... it works fine

**Comment by benfry** [comment] 2023-03-07 16:24
May be related to #527.

**Comment by benfry** [comment] 2023-07-16 18:28
Closing as duplicate of https://github.com/processing/processing4/issues/527

**Closed as completed by benfry** 2023-07-16 18:28 UTC
Labels: Duplicate
